services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./backend/logs:/app/logs

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:8000
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend
